import type { Language } from "./domain/models";

const en = {
  settings: "Settings", circles: "Your events", homeEyebrow: "Choose the gathering", homeTitleA: "Meet together.", homeTitleB: "Split fairly.", homeCopy: "Choose an event and begin. Group setup stays one tap away whenever details change.",
  createTitle: "Create a new event", renameTitle: "Rename the event", groupPlaceholder: "e.g. Friday dinner", save: "Save", create: "Create", firstGroup: "Your first event starts here", firstGroupCopy: "Create a family gathering, trip, friends' night, or any shared event.", startEvent: "Start event", continueEvent: "Continue event", draftLabel: "Saved draft", manageGroup: "Manage group", rename: "Rename", delete: "Delete",
  allEvents: "All events", groupSetup: "Group setup", peopleReady: "people ready", startGathering: "Start gathering", whoPays: "Who pays together?", billingUnits: "Billing units", unitPlaceholder: "e.g. The Cohen family", add: "Add", member: "member", members: "members", selectUnit: "Select a unit", people: "People", memberName: "Member name", birthDate: "Birth date", manualWeight: "Manual weight", notes: "Notes (optional)", active: "Active", saveMember: "Save member", addMember: "Add member", noMembers: "No members yet.", born: "Born", weight: "Weight", defaultWeight: "Default weight",
  backToEvents: "Save & exit", editGroup: "Edit group", saveDraft: "Save", draftSaved: "Saved", gatheringDate: "Gathering date", whoIsHere: "Who’s at the table?", of: "of", attending: "attending", attendance: "Attendance", chooseJoined: "Choose who joined", expenses: "Expenses", addPaid: "Add what was paid", settle: "Settle", finalSplit: "See the final split", temporaryNote: "Your progress is saved on this device. Reset starts this event over.", moneyIn: "Money in", whatPaid: "What was paid?", total: "Total", paidBy: "Paid by", amount: "Amount", description: "Description", optional: "optional", descPlaceholder: "Groceries, dinner, tickets…", addExpense: "Add expense", noExpenses: "No expenses yet", noExpensesCopy: "Add the first payment to start the live total.", expense: "Expense", unknownUnit: "Unknown unit", deleteExpense: "Delete expense", receipt: "Receipt", takeReceipt: "Photograph receipt", changeReceipt: "Change photo", removeReceipt: "Remove photo", scanningReceipt: "Reading receipt", receiptAmountFound: "Amount detected — check it before adding", receiptAmountMissing: "No amount found. Enter it manually.", receiptScanFailed: "Couldn’t read the receipt. Enter the amount manually.", cameraHint: "The photo and OCR stay on this device.", ocrFirstUse: "The first scan may take a moment.",
  finishLine: "The finish line", settledSimply: "Settled, simply.", copied: "Copied", copyReport: "Copy report", reset: "Reset", chooseAttendee: "Choose at least one attendee to calculate shares.", addExpensePrompt: "Add an expense and the settlement will appear here instantly.", totalSpent: "Total spent", totalWeight: "Total weight", perShare: "Per full share", billingUnit: "Billing unit", paid: "Paid", share: "Share", balance: "Balance", whoPaysWhom: "Who pays whom", pays: "pays", allSettled: "All settled", settlement: "Settlement", everyoneSettled: "Everyone is settled.", weightedParticipants: "Weighted participants", thanks: "Thanks everyone!",
  makeYours: "Make it yours", settingsTitleA: "Settings,", settingsTitleB: "not clutter.", settingsCopy: "One set of defaults, used instantly across every group.", money: "Money", moneyCopy: "Choose the currency and how final shares are rounded.", currency: "Currency", rounding: "Rounding", exactCents: "Exact cents", nearestHalf: "Nearest 0.50", nearestWhole: "Nearest whole unit", participantWeight: "Participant weight", weightCopy: "Use ages automatically, or maintain a weight per member.", automatic: "Automatic", manual: "Manual", childUnder: "Child under age", childWeight: "Child weight", ageTip: "Ages are calculated on each gathering date.", reportFooter: "Report footer", footerCopy: "This line appears at the end of every copied settlement report.", footerText: "Footer text", back: "Back", returnToEvent: "Back to event", eventName: "Event name", eventNamePlaceholder: "e.g. Summer family weekend", shareGroup: "Share", sharedGroup: "Shared", syncing: "Syncing…", synced: "Synced", syncError: "Sync problem",
} as const;

const he: Record<keyof typeof en, string> = {
  settings: "הגדרות", circles: "האירועים שלכם", homeEyebrow: "בחירת אירוע", homeTitleA: "נפגשים יחד.", homeTitleB: "מתחלקים בהוגנות.", homeCopy: "בחרו אירוע והתחילו. הגדרת המשפחה או הקבוצה נשארת זמינה בלחיצה אחת.",
  createTitle: "יצירת אירוע חדש", renameTitle: "שינוי שם האירוע", groupPlaceholder: "לדוגמה: ארוחת שישי", save: "שמירה", create: "יצירה", firstGroup: "האירוע הראשון מתחיל כאן", firstGroupCopy: "צרו מפגש משפחתי, טיול, ערב חברים או כל אירוע משותף.", startEvent: "התחלת אירוע", continueEvent: "המשך האירוע", draftLabel: "טיוטה שמורה", manageGroup: "הגדרת הקבוצה", rename: "שינוי שם", delete: "מחיקה",
  allEvents: "כל האירועים", groupSetup: "הגדרת הקבוצה", peopleReady: "אנשים מוכנים", startGathering: "התחלת אירוע", whoPays: "מי משלמים יחד?", billingUnits: "יחידות חיוב", unitPlaceholder: "לדוגמה: משפחת כהן", add: "הוספה", member: "חבר", members: "חברים", selectUnit: "בחרו יחידה", people: "אנשים", memberName: "שם החבר", birthDate: "תאריך לידה", manualWeight: "משקל ידני", notes: "הערות (לא חובה)", active: "פעיל", saveMember: "שמירת חבר", addMember: "הוספת חבר", noMembers: "עדיין אין חברים.", born: "תאריך לידה", weight: "משקל", defaultWeight: "משקל ברירת מחדל",
  backToEvents: "שמירה ויציאה", editGroup: "עריכת המשפחה", saveDraft: "שמירה", draftSaved: "נשמר", gatheringDate: "תאריך האירוע", whoIsHere: "מי סביב השולחן?", of: "מתוך", attending: "משתתפים", attendance: "נוכחות", chooseJoined: "בחרו מי הגיע", expenses: "הוצאות", addPaid: "הוסיפו מה שולם", settle: "התחשבנות", finalSplit: "צפו בחלוקה הסופית", temporaryNote: "ההתקדמות נשמרת במכשיר. איפוס מתחיל את האירוע מחדש.", moneyIn: "הכסף ששולם", whatPaid: "מה שולם?", total: "סה״כ", paidBy: "שולם על ידי", amount: "סכום", description: "תיאור", optional: "לא חובה", descPlaceholder: "קניות, ארוחה, כרטיסים…", addExpense: "הוספת הוצאה", noExpenses: "עדיין אין הוצאות", noExpensesCopy: "הוסיפו את התשלום הראשון כדי להתחיל את החישוב.", expense: "הוצאה", unknownUnit: "יחידה לא ידועה", deleteExpense: "מחיקת הוצאה", receipt: "קבלה", takeReceipt: "צילום קבלה", changeReceipt: "החלפת צילום", removeReceipt: "הסרת צילום", scanningReceipt: "קורא את הקבלה", receiptAmountFound: "הסכום זוהה — כדאי לבדוק לפני ההוספה", receiptAmountMissing: "לא זוהה סכום. אפשר להזין אותו ידנית.", receiptScanFailed: "לא הצלחנו לקרוא את הקבלה. אפשר להזין סכום ידנית.", cameraHint: "הצילום והזיהוי נשארים במכשיר הזה.", ocrFirstUse: "הסריקה הראשונה עשויה לקחת רגע.",
  finishLine: "קו הסיום", settledSimply: "החשבון נסגר.", copied: "הועתק", copyReport: "העתקת דוח", reset: "איפוס", chooseAttendee: "בחרו לפחות משתתף אחד כדי לחשב את החלוקה.", addExpensePrompt: "הוסיפו הוצאה וההתחשבנות תופיע כאן מיד.", totalSpent: "סך ההוצאות", totalWeight: "משקל כולל", perShare: "עלות למנה מלאה", billingUnit: "יחידת חיוב", paid: "שולם", share: "חלק יחסי", balance: "יתרה", whoPaysWhom: "מי משלם למי", pays: "משלם ל־", allSettled: "כולם מאוזנים", settlement: "התחשבנות", everyoneSettled: "אין צורך בהעברות.", weightedParticipants: "משתתפים משוקללים", thanks: "תודה לכולם!",
  makeYours: "התאמה אישית", settingsTitleA: "הגדרות,", settingsTitleB: "בלי עומס.", settingsCopy: "ברירות מחדל פשוטות שמשפיעות מיד על כל הקבוצות.", money: "כסף", moneyCopy: "בחרו מטבע ואופן עיגול לחלוקה הסופית.", currency: "מטבע", rounding: "עיגול", exactCents: "דיוק של אגורות", nearestHalf: "לחצי היחידה הקרובה", nearestWhole: "ליחידה השלמה הקרובה", participantWeight: "משקל משתתפים", weightCopy: "חישוב אוטומטי לפי גיל או משקל ידני לכל חבר.", automatic: "אוטומטי", manual: "ידני", childUnder: "ילד מתחת לגיל", childWeight: "משקל ילד", ageTip: "הגיל מחושב לפי תאריך כל אירוע.", reportFooter: "סיום הדוח", footerCopy: "השורה הזו תופיע בסוף כל דוח התחשבנות שמועתק.", footerText: "טקסט סיום", back: "חזרה", returnToEvent: "חזרה לאירוע", eventName: "שם האירוע", eventNamePlaceholder: "לדוגמה: שבת משפחתית קיץ תשפ״ו", shareGroup: "שיתוף", sharedGroup: "משותף", syncing: "מסנכרן…", synced: "מסונכרן", syncError: "בעיית סנכרון",
};

export type TranslationKey = keyof typeof en;
export const translate = (language: Language, key: TranslationKey): string => (language === "he" ? he : en)[key];
